export const OPEN_CHAT      = 'OPEN_CHAT';
export const CLOSE_CHAT     = 'CLOSE_CHAT';
export const CREATE_CHANNEL = 'CREATE_CHANNEL';
export const DELETE_CHANNEL = 'DELETE_CHANNEL';
export const OPEN_CHANNEL = 'OPEN_CHANNEL';

// User status constants
export const SET_USER_STATUS = 'SET_USER_STATUS';


export const OPEN_DIRECT_MESSAGE  = 'OPEN_DIRECT_MESSAGE';
export const CLOSE_DIRECT_MESSAGE = 'CLOSE_DIRECT_MESSAGE';

export const SEND_MESSAGE      = 'SEND_MESSAGE';
export const MODIFY_MESSAGE    = 'MODIFY_MESSAGE';
export const DELETE_MESSAGE    = 'DELETE_MESSAGE';
export const OPEN_CHAT_WINDOW  = 'OPEN_CHAT_WINDOW';
export const CLOSE_CHAT_WINDOW = 'CLOSE_CHAT_WINDOW';

export const SEND_CHANNEL_MESSAGE = 'SEND_CHANNEL_MESSAGE';
export const SEND_DIRECT_MESSAGE  = 'SEND_DIRECT_MESSAGE';